on:
  workflow_dispatch:
    branches:
      - "main"

jobs:
  Upload_coverage:
    runs-on: ubuntu-latest
    name: Upload coverage tests to Codecov.io
    container:
      image: epitechcontent/epitest-docker:latest
      volumes:
        - "tests-volume:/upload_volume_mount"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the unitary tests
        run: make re tests_run upload_test
        timeout-minutes: 2
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/
          flags: unit-tests
          gcov: true
          fail_ci_if_error: true
